### ISSUE TITLE
whats i need?

### ISSUE THREAD

**Issue by FrenzY8** [KatowProject/Kato-Bot#35]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../config/config.json'
Require stack:
- C:\Kato-Bot-master\handler\ClientBuilder.js
- C:\Kato-Bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at new katopos (C:\Kato-Bot-master\handler\ClientBuilder.js:12:19)
    at Object.<anonymous> (C:\Kato-Bot-master\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Kato-Bot-master\\handler\\ClientBuilder.js',
    'C:\\Kato-Bot-master\\index.js'
  ]
}
The syntax of the command is incorrect.
Press any key to continue . . .

**Comment by KatowProject** [comment]
rename file `config.example.json` to `config.json` in `config/` path

**Comment by KatowProject** [comment]
https://github.com/KatowProject/Kato-Bot/blob/f6d0120f3dfea698c8cb95ded2fd14e2658b1bd8/config/config.example.json

**Comment by FrenzY8** [comment]
the first time escaping, it worked, the second time I got

internal/modules/cjs/loader.js:1131
    throw err;
    ^

SyntaxError: C:\Kato-Bot-master\config\config.json: Unexpected token ] in JSON at position 128
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at new katopos (C:\Kato-Bot-master\handler\ClientBuilder.js:12:19)
    at Object.<anonymous> (C:\Kato-Bot-master\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
The syntax of the command is incorrect.
Press any key to continue . . .

**Comment by KatowProject** [comment]
maybe typo syntax in `config.json`
let's try to check the file again

no error in my json file
```json
{
    "discord": {
        "owners": [
            "458342161474387999"
        ],
        "prefix": [
            "k!",
            "k."
        ],
        "token": "my token"
    }
}
```

**Comment by FrenzY8** [comment]
tysm for the respons dudes
